### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by andrewpros** [glmn/CrossoutItems#1]
Hi.
There are some icons missing, raids difficulty, invasion, crafting, probably more.

Example https://vignette.wikia.nocookie.net/crossout/images/9/9e/%D0%92%D1%82%D0%BE%D1%80%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B8%D0%BA%D0%BE%D0%BD%D0%BA%D0%B0.png/revision/latest?cb=20171207074512&format=original&path-prefix=ru

**Comment by glmn** [comment]
Hi!
I don't have enough time to maintain this repo. 
You can create a pull request, so i will accept it.
